### ISSUE TITLE
感染症対策特集

### ISSUE THREAD

**Issue by nsxiu** [CurveTechLimited/2019-ncov#8]
1. 
标题：新型コロナウイルスに関するQ&A（一般の方向け）
链接：https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/dengue_fever_qa_00001.html

2. 
标题：新型コロナウイルス感染症に備えて　～一人ひとりができる対策を知っておこう～
链接：http://www.kantei.go.jp/jp/headline/kansensho/coronavirus.html

**Comment by wowlusitong** [comment]
这个属于json数据上的修改，我先把这个两个填充上
